import type { Metadata } from "next";
import type { AppProps } from 'next/app'

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 
export default function App({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />
}